Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dhcp-server-centos"
    vb.memory = "512"
  end

  config.vm.hostname = "dhcp-server-centos"
	

  config.vm.provision "shell", path: "provision.sh"
end