Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker"
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.hostname = "docker"

  config.vm.synced_folder ".", "/home/vagrant/code",
    owner: "www-data", group: "www-data"

  config.vm.provision "shell", path: "provision.sh"
end