Vagrant.configure("2") do |config|
  config.vm.box = "alpine/alpine64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dhcp-client-alpine"
  end

  config.vm.hostname = "dhcp-client-alpine"
	

  config.vm.provision "shell", path: "provision.sh"
end