Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dhcp-server-ubuntu"
    vb.memory = "512"
    vb.cpus = 2
  end

  config.vm.hostname = "dhcp-server-ubuntu"
	

  config.vm.provision "shell", path: "provision.sh"
end